### ISSUE TITLE
mdbook-epub 无法编译

### ISSUE THREAD

**Issue by ipconfiger** [easychen/one-person-businesses-methodology-v2.0#2]
```
mdbook-epub --standalone true ./one-person-businesses-methodology-v2.0/
Running mdbook-epub as standalone app...
thread 'main' panicked at /Users/alex/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/mdbook-epub-0.4.37/src/generator.rs:349:63:
Failed to find cover image by full path-name = "./one-person-businesses-methodology-v2.0/src/src/images/opb-book-cover.jpg": Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by easychen** [comment]
相对路径错了，进目录去执行命令。

**Comment by ZhangHalfGod** [comment]
1、download   rustup-init.exe
2、cargo install mdbook   
3、cargo install mdbook-epub
4、in  dir  D:\trae_git\easychen\one-person-businesses-methodology-v2.0-master   exchang  book.toml

before:
[output.epub]
cover-image = "src/images/opb-book-cover-2.1.jpg"

after:
[output.epub]
---->cover-image = "images/opb-book-cover-2.1.jpg"

5、you need delete   url   opb-book-cover-2.1.jpg   in  anywhere 

(1)D:\trae_git\easychen\one-person-businesses-methodology-v2.0-master   --> in  README.md   --->  delete  opb-book-cover-2.1.jpg 

(2)D:\trae_git\easychen\one-person-businesses-methodology-v2.0-master\src  ---> in README.md ---> delete  opb-book-cover-2.1.jpg 

then you  can  powershell   use cmd

6、 in  dir     D:\trae_git\easychen  open cmd   --->     mdbook-epub --standalone ./one-person-businesses-methodology-v2.0-master/

such as : PS D:\trae_git\easychen> mdbook-epub --standalone ./one-person-businesses-methodology-v2.0-master/

Final : find dir D:\trae_git\easychen\one-person-businesses-methodology-v2.0-master\book  --->   .epub   file   OK!!!

**Comment by ZhangHalfGod** [comment]
> ```
> mdbook-epub --standalone true ./one-person-businesses-methodology-v2.0/
> Running mdbook-epub as standalone app...
> thread 'main' panicked at /Users/alex/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/mdbook-epub-0.4.37/src/generator.rs:349:63:
> Failed to find cover image by full path-name = "./one-person-businesses-methodology-v2.0/src/src/images/opb-book-cover.jpg": Os { code: 2, kind: NotFound, message: "No such file or directory" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

use my answer  that's OK!!

**Comment by conclave619** [comment]
thx

sunshine ***@***.***>于2025年8月29日 周五11:23写道：
